name: Deploy DEV
on:
  workflow_dispatch:

jobs:

  Security_check:
    name: Security Check
    runs-on: self-hosted
    steps:
      
      - name: Generate a token
        if : github.event_name == 'workflow_dispatch'
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Check DAT-DAPP-ADMINS User Membership
        if : github.event_name == 'workflow_dispatch'
        uses: marcocarvalho/team-membership@v3
        id: checkUserMember
        with:
          username: ${{ github.actor }}
          team: 'DAT-DAPP-ADMINS'
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token}}

      - if: ${{ steps.checkUserMember.outputs.isTeamMember == 'true' }}
        run: exit 0

      - if: ${{ steps.checkUserMember.outputs.isTeamMember == 'false' }}
        run: exit 1

  
      - name: Check DAT-DAPP-ADMINS User Membership
        if: github.event_name == 'pull_request_review' && github.event.review.state == 'APPROVED'
        uses: marcocarvalho/team-membership@v3
        id: checkPRUserMember
        with:
          username: ${{ github.event.review.user.login }}
          team: 'DAT-DAPP-ADMINS'
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
  
      - name: Verify PR Approval by DAT-DAPP-ADMINS
        if: github.event_name == 'pull_request_review' && github.event.action == 'submitted' && steps.checkPRUserMember.outputs.isTeamMember == 'true'
        run: |
          echo "PR is approved by a member of DAT-DAPP-ADMINS."
  
      - name: Exit if not approved by DAT-DAPP-ADMINS
        if: github.event_name == 'pull_request_review' && github.event.action == 'submitted' && steps.checkUserMember.outputs.isTeamMember == 'false'
        run: exit 1
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run a one-line script
        run: echo Hello, world for DEV!

