name: Team membership check

on:
  workflow_dispatch:
  
  push:
    branches:
      - develop
      
  pull_request:
    branches:
      - develop

  pull_request_review:
    types: 
      - submitted

jobs:
  Security_check:
    name: Security Check
    runs-on: ubuntu-latest
    steps:

      - name: Check membership on workflow_dispatch
        if: github.event_name == 'workflow_dispatch'
        uses: marcocarvalho/team-membership@v3
        id: checkUserMember
        with:
          organization: ${{ github.repository_owner }}
          username: ${{ github.actor }}
          team: 'DAT-DAPP-ADMINS'
          GITHUB_TOKEN: ${{ secrets.DAPP_PAT_TOKEN_GITHUB }}

      - if: steps.checkUserMember.outputs.isTeamMember == 'true' 
        run: exit 0

      - if: steps.checkUserMember.outputs.isTeamMember == 'false'
        run: exit 1


      - name: Check membership on Pull request Reviewed
        if: github.event_name == 'pull_request_review' && github.event.review.state == 'APPROVED'
        uses: marcocarvalho/team-membership@v3
        id: checkPRUserMember
        with:
          organization: ${{ github.repository_owner }}
          username: ${{ github.event.review.user.login }}
          team: 'DAT-DAPP-ADMINS'
          GITHUB_TOKEN: ${{ secrets.DAPP_PAT_TOKEN_GITHUB }} 

      - if: github.event_name == 'pull_request_review' && github.event.action == 'submitted' &&  steps.checkPRUserMember.outputs.isTeamMember == 'true'
        run: exit 0

      - if: github.event_name == 'pull_request_review' && github.event.action == 'submitted' &&  steps.checkPRUserMember.outputs.isTeamMember == 'false'
        run: exit 1

  deploy-dev:
    needs: Security_check
    name: Deploy-plan
    runs-on: ubuntu-latest
    steps:
      - name: print something
        run: echo hello from security check!
        
  
