name: Testing for github context
on:
  workflow_dispatch:

  pull_request:
  
jobs:
  check_github_context:
    name: check github context
    runs-on: unbuntu-latest

    steps:
      - name: check github contxt for github.event
        if: github.event == "workflow_disptach"
        run: echo "This workflow is triggered by the event of workflow_dispatch
        
      - name: check github contxt for github.event
        if: github.event == "pull_request"
        run: echo "This workflow is triggered by the event of workflow_dispatch"

      - name: check github contxt for github.event
        if: github.event == "pull_request"
        run: echo "This workflow is triggered by the event of workflow_dispatch"

      
        
  
